// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RichasyAssistant.Libs.Database;

#nullable disable

namespace RichasyAssistant.Libs.Database.Migrations
{
    [DbContext(typeof(TranslationDbContext))]
    [Migration("20231106055559_InitializeTranslationDbContext")]
    partial class InitializeTranslationDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("RichasyAssistant.Models.App.Kernel.Metadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageListId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Translate.LanguageList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Kernel.Metadata", b =>
                {
                    b.HasOne("RichasyAssistant.Models.App.Translate.LanguageList", null)
                        .WithMany("Langauges")
                        .HasForeignKey("LanguageListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Translate.LanguageList", b =>
                {
                    b.Navigation("Langauges");
                });
#pragma warning restore 612, 618
        }
    }
}
