// Copyright (c) Richasy Assistant. All rights reserved.
// <auto-generated />

namespace RichasyAssistant.App.Controls.Markdown;

public interface IImageProvider
{
    Task<Image> GetImage(string url);
    bool ShouldUseThisProvider(string url);
}
