// Copyright (c) Richasy Assistant. All rights reserved.
// <auto-generated />

namespace RichasyAssistant.App.Controls.Markdown;

public interface ISVGRenderer
{
    Task<Image> SvgToImage(string svgString);
}
