// Copyright (c) Richasy Assistant. All rights reserved.
// <auto-generated />

using Microsoft.UI.Xaml.Documents;

namespace RichasyAssistant.App.Controls.Markdown.TextElements;

public interface IAddChild
{
    TextElement TextElement { get; }
    void AddChild(IAddChild child);
}
