// Copyright (c) Richasy Assistant. All rights reserved.
// <auto-generated />

using Markdig.Syntax.Inlines;
using Microsoft.UI.Xaml.Documents;
using Microsoft.UI.Xaml.Media.Media3D;

namespace RichasyAssistant.App.Controls.Markdown.TextElements;

internal class MyInlineCode : IAddChild
{
    private readonly CodeInline _codeInline;
    private InlineUIContainer _inlineContainer;
    private readonly MarkdownConfig _config;

    public TextElement TextElement => _inlineContainer;

    public MyInlineCode(CodeInline codeInline, MarkdownConfig config)
    {
        _codeInline = codeInline;
        _config = config;
        _inlineContainer = new InlineUIContainer();
        var border = new Border
        {
            VerticalAlignment = VerticalAlignment.Bottom,
            Background = _config.Themes.InlineCodeBackground,
            BorderBrush = _config.Themes.InlineCodeBorderBrush,
            BorderThickness = _config.Themes.InlineCodeBorderThickness,
            CornerRadius = _config.Themes.InlineCodeCornerRadius,
            Padding = _config.Themes.InlineCodePadding,
        };
        var transform = new CompositeTransform3D
        {
            TranslateY = 6,
        };
        border.Transform3D = transform;
        var textBlock = new TextBlock
        {
            FontSize = _config.Themes.InlineCodeFontSize,
            FontWeight = _config.Themes.InlineCodeFontWeight,
            Text = codeInline.Content.ToString(),
            IsTextSelectionEnabled = true,
        };
        border.Child = textBlock;
        _inlineContainer.Child = border;
    }

    public void AddChild(IAddChild child)
    {
    }
}
