// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RichasyAssistant.Models.Context;

#nullable disable

namespace RichasyAssistant.Models.Context.Migrations
{
    [DbContext(typeof(TranslationDbContext))]
    [Migration("20231106111427_InitializeTranslationDb")]
    partial class InitializeTranslationDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("RichasyAssistant.Models.App.Kernel.Metadata", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageListId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LanguageListId");

                    b.ToTable("Metadata");
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Translate.LanguageList", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Translate.TranslationRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetLanguage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Kernel.Metadata", b =>
                {
                    b.HasOne("RichasyAssistant.Models.App.Translate.LanguageList", null)
                        .WithMany("Langauges")
                        .HasForeignKey("LanguageListId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RichasyAssistant.Models.App.Translate.LanguageList", b =>
                {
                    b.Navigation("Langauges");
                });
#pragma warning restore 612, 618
        }
    }
}
