// <auto-generated />
// Copyright (c) Richasy Assistant. All rights reserved.

namespace RichasyAssistant.Models.Constants;

/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    DefaultTemperature,
    DefaultMaxResponseTokens,
    DefaultTopP,
    DefaultFrequencyPenalty,
    DefaultPresencePenalty,

    AzureOpenAIAccessKey,
    AzureOpenAIEndpoint,
    AzureOpenAIChatModelName,
    AzureOpenAIEmbeddingModelName,
    AzureOpenAICompletionModelName,

    OpenAIAccessKey,
    OpenAIOrganization,
    OpenAICustomEndpoint,
    OpenAIChatModelName,
    OpenAIEmbeddingModelName,
    OpenAICompletionModelName,

    AzureTranslateKey,
    AzureTranslateRegion,

    BaiduTranslateAppId,
    BaiduTranslateAppKey,

    AzureSpeechKey,
    AzureSpeechRegion,

    AzureWhisperKey,
    AzureWhisperModelName,
    AzureWhisperEndpoint,

    AzureImageKey,
    AzureImageEndpoint,

    OpenAIWhisperKey,
    OpenAIImageKey,

    LibraryFolderPath,
    DefaultChatDbPath,
    DefaultSecretDbPath,

    IsAutoGenerateSessionTitle,
    IsFirstLaunch,
    IsStartupOpen,
    SkipWelcome,
    DefaultKernel,
    DefaultTranslate,
    DefaultSpeech,
    DefaultImage,
}
