// <auto-generated />
// Copyright (c) Richasy Assistant. All rights reserved.

namespace RichasyAssistant.Models.Constants;

/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    DefaultTemperature,
    DefaultMaxResponseTokens,
    DefaultTopP,
    DefaultFrequencyPenalty,
    DefaultPresencePenalty,

    AzureOpenAIAccessKey,
    AzureOpenAIEndpoint,
    DefaultAzureOpenAIChatModelName,

    OpenAIAccessKey,
    OpenAIOrganization,
    OpenAICustomEndpoint,
    DefaultOpenAIChatModelName,

    AzureTranslateKey,
    AzureTranslateRegion,

    BaiduTranslateAppId,
    BaiduTranslateAppKey,

    AzureSpeechKey,
    AzureSpeechRegion,

    AzureWhisperKey,
    DefaultAzureWhisperModelName,
    AzureWhisperEndpoint,

    AzureImageKey,
    AzureImageEndpoint,

    OpenAIWhisperKey,
    OpenAIImageKey,

    LibraryFolderPath,
    LocalFolderPath,
    DefaultChatDbPath,
    DefaultSecretDbPath,
    DefaultTranslationDbPath,
    DefaultDrawDbPath,

    IsAutoGenerateSessionTitle,
    IsStartupOpen,
    SkipWelcome,
    DefaultKernel,
    DefaultTranslate,
    DefaultSpeech,
    DefaultDrawService,
    UseStreamOutput,
    TranslationSourceLanguage,
    TranslationTargetLanguage,
    LastWindowWidth,
    LastWindowHeight,
    IsWindowMaximized,
    LastOpenedPage,
    ChatListColumnWidth,
    ChatListType,
    LastOpenSessionId,
    RecordTranslationResult,
    DrawImageSize,
    DrawHistoryColumnWidth,
    AzureSpeechTTSColumnWidth,
    AzureTextToSpeechLanguage,
    AzureTextToSpeechVoice,
    CurrentSpeechType,
    AzureContinuousSpeechRecognize,
    StorageSearchType,
    MaxStorageSearchCount,
    IsStoragePageGridLayout,
    StorageSortType,
    AppTheme,
    UseMarkdownRenderer,
    CustomKernelId,
    CustomDrawId,
    CustomTranslateId,
    CustomSpeechId,
}
