// <auto-generated />
// Copyright (c) Reader Copilot. All rights reserved.

namespace RichasyAssistant.Models.Constants;

/// <summary>
/// 设置名称.
/// </summary>
public enum SettingNames
{
    DefaultTemperature,
    DefaultMaxResponseTokens,
    DefaultTopP,
    DefaultFrequencyPenalty,
    DefaultPresencePenalty,

    AzureOpenAIAccessKey,
    AzureOpenAIEndpoint,
    AzureOpenAIChatModelName,
    AzureOpenAIEmbeddingModelName,
    AzureOpenAICompletionModelName,

    OpenAIAccessKey,
    OpenAIOrganization,
    OpenAICustomEndpoint,
    OpenAIChatModelName,
    OpenAIEmbeddingModelName,
    OpenAICompletionModelName,

    LibraryFolderPath,
    DefaultChatDbPath,

    IsAutoGenerateSessionTitle,
}
