// Copyright (c) Richasy Assistant. All rights reserved.
// <auto-generated />

using Markdig.Renderers;
using Markdig.Syntax;

namespace RichasyAssistant.App.Controls.Markdown.Renderers;

public abstract class WinUIObjectRenderer<TObject> : MarkdownObjectRenderer<WinUIRenderer, TObject>
where TObject : MarkdownObject
{
}
